### model
model_name_or_path: Qwen/Qwen3.5-2B
image_max_pixels: 65536
trust_remote_code: true
flash_attn: fa2
enable_liger_kernel: true
### method
stage: sft
do_train: true
finetuning_type: lora
freeze_vision_tower: true
freeze_multi_modal_projector: false
disable_gradient_checkpointing: true
### LoRA
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target: all
### data
dataset: duck_vlm_sft
dataset_dir: duck_vlm/train/data
template: qwen3_5_nothink
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4
dataloader_persistent_workers: true
dataloader_pin_memory: true
### output
output_dir: saves/duck-vlm/qwen3.5-2b-lora
logging_steps: 2
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
run_name: duck-vlm-qwen3.5-2b-lora
### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 12.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000